# Generated by Django 3.0.5 on 2020-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('on_map', models.IntegerField()),
            ],
        ),
    ]
