# Generated by Django 3.0.5 on 2020-04-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='id_on_map',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
