# Generated by Django 3.0.5 on 2020-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_landmark_id_on_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='xcor',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landmark',
            name='ycor',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
