# Generated by Django 3.0.5 on 2020-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20200411_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='on_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
