# Generated by Django 3.0.5 on 2020-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200428_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='color',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
