# Generated by Django 3.0.5 on 2020-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_landmark_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='color',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
